Traceback (most recent call last):
  File "C:\Users\ans15\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\ans15\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ans15\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ans15\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ans15\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\ans15\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ans15\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ans15\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('total training rock images:', len(os.listdir(rock_dir)))
print('total training paper images:', len(os.listdir(paper_dir)))
print('total training scissors images:', len(os.listdir(scissors_dir)))

rock_files = os.listdir(rock_dir)
paper_files = os.listdir(paper_dir)
scissors_files = os.listdir(scissors_dir)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_103244/2741649598.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mprint[0m[1;33m([0m[1;34m'total training rock images:'[0m[1;33m,[0m [0mlen[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mlistdir[0m[1;33m([0m[0mrock_dir[0m[1;33m)[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mprint[0m[1;33m([0m[1;34m'total training paper images:'[0m[1;33m,[0m [0mlen[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mlistdir[0m[1;33m([0m[0mpaper_dir[0m[1;33m)[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mprint[0m[1;33m([0m[1;34m'total training scissors images:'[0m[1;33m,[0m [0mlen[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mlistdir[0m[1;33m([0m[0mscissors_dir[0m[1;33m)[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [0mrock_files[0m [1;33m=[0m [0mos[0m[1;33m.[0m[0mlistdir[0m[1;33m([0m[0mrock_dir[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'data/rps/rock'
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'data/rps/rock'

